cargo-features = ["edition2024"]

[package]
name = "s2"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "example-1"
path = "src/examples/example_1.rs"

[[bin]]
name = "example-2"
path = "src/examples/example_2.rs"

[dependencies]
itertools = "0.14.0"
strum = "0.27.1"
strum_macros = "0.27.1"
